---
- name: Test AAP to OCP Playbook
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Create a secondary network bridge
      redhat.openshift.k8s:
        state: present
        definition:
          apiVersion: 'nmstate.io/v1'
          kind: 'NodeNetworkConfigurationPolicy'
          metadata:
            name: 'enp9s0-nncp'
            annotations:
              description: 'policy to configure enp9s0 which is connected to subnet 160'
          spec:
            nodeSelector:
              node-role.kubernetes.io/worker: ''
            desiredState:
              ovn:
                bridge-mappings:
                  - bridge: 'ovs-br1'
                    localnet: 'localnet-160'
                    state: 'present'
              interfaces:
                # The bridge connecting ovs virtual port to physical port
                - name: 'ovs-br1'
                  type: 'ovs-bridge'
                  state: 'up'
                  bridge:
                    allow-extra-patch-ports: true
                    options:
                      stp:
                        enabled: false
                      mcast-snooping-enable: true
                    port:
                      - name: 'enp9s0'
                      - name: 'ovs-br1'
                # The Virtual Port
                - name: 'ovs-br1'
                  type: 'ovs-interface'
                  state: 'up'
                  ipv4:
                    enabled: false
                  ipv6:
                    enabled: false
