---
- name: Test AAP to OCP Playbook
  hosts: localhost

  vars:
    namespace_name: foobar
    vm_name: my-vm-one
    vm_username: myusername
    vm_password: mypassword
    vm_storage_size: 30Gi
    vm_instance_type: u1.small
    vm_machine_type: pc-q35-rhel9.6.0
    storageclass_name: nfs-client
    datasource_name: fedora
    datasource_namespace_name: openshift-virtualization-os-images

  tasks:
    - name: Create a VM with Host Passthrough
      redhat.openshift.k8s:
        state: present
        definition:
          apiVersion: kubevirt.io/v1
          kind: VirtualMachine
          metadata:
            name: "{{ vm_name }}"
            namespace: "{{ namespace_name }}"
          spec:
            dataVolumeTemplates:
              - metadata:
                  name: "{{ vm_name }}-volume"
                spec:
                  sourceRef:
                    kind: DataSource
                    name: "{{ datasource_name }}"
                    namespace: "{{ datasource_namespace_name }}"
                  storage:
                    resources:
                      requests:
                        storage: "{{ vm_storage_size }}"
                    storageClassName: "{{ storageclass_name }}"
            instancetype:
              kind: VirtualMachineClusterInstancetype
              name: u1.small
            runStrategy: Halted
            template:
              spec:
                architecture: amd64
                domain:
                  cpu:
                    model: host-passthrough
                  devices:
                    autoattachPodInterface: false
                    disks:
                      - bootOrder: 1
                        name: rootdisk
                    interfaces:
                      - masquerade: {}
                        name: default
                  machine:
                    type: "{{ vm_machine_type }}"
                  resources: {}
                networks:
                  - name: default
                    pod: {}
                nodeSelector:
                  node-role.kubernetes.io/worker: ''
                subdomain: headless
                volumes:
                  - dataVolume:
                      name: "{{ vm_name }}-volume"
                    name: rootdisk
                  - cloudInitNoCloud:
                      userData: |
                        #cloud-config
                        chpasswd:
                          expire: false
                        password: "{{ vm_password }}"
                        user: "{{ vm_username }}"
                    name: cloudinitdisk